In [2]:
import pandas as pd

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#to ignore warnings
import warnings
warnings.filterwarnings('ignore')

Matplotlib is building the font cache; this may take a moment.

In [4]:
data = pd.read_csv("cars_ds_final_2021.csv")

In [5]:
data.head()

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data.tail()

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
1262,1262,Bmw,X5,Xdrive30D Xline,"Rs. 82,90,000",2993 cc,6.0,4.0,AWD (All Wheel Drive),In-line,...,Yes,Yes,NaN,Yes,Yes,NaN,Yes,Yes,NaN,NaN
1263,1263,Bmw,X5,Xdrive40I M Sport,"Rs. 82,90,000",2998 cc,6.0,4.0,AWD (All Wheel Drive),In-line,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1264,1264,Mahindra,Alturas G4,2Wd At,"Rs. 27,70,150",2157 cc,4.0,NaN,FWD (Front Wheel Drive),In-line,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1265,1265,Mahindra,Alturas G4,4Wd At,"Rs. 30,70,150",2157 cc,4.0,4.0,4WD,In-line,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1266,1266,Ferrari,812 Superfast,Superfast,"Rs. 5,20,00,000",6496 cc,12.0,NaN,AWD (All Wheel Drive),V,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Columns: 141 entries, Unnamed: 0 to Electric_Range
dtypes: float64(9), int64(1), object(131)
memory usage: 1.4+ MB

In [8]:
data.nunique()

Unnamed: 0           1267
Make                   39
Model                 263
Variant              1048
Ex-Showroom_Price    1162
                     ...
USB_Ports               3
Heads-Up_Display        1
Welcome_Lights          1
Battery                 5
Electric_Range          8
Length: 141, dtype: int64

In [9]:
data.isnull().sum()

Unnamed: 0              0
Make                   75
Model                   0
Variant                 0
Ex-Showroom_Price       0
                     ...
USB_Ports            1242
Heads-Up_Display     1216
Welcome_Lights       1198
Battery              1254
Electric_Range       1250
Length: 141, dtype: int64

In [10]:
(data.isnull().sum()/(len(data)))*100

Unnamed: 0            0.000000
Make                  5.919495
Model                 0.000000
Variant               0.000000
Ex-Showroom_Price     0.000000
                       ...
USB_Ports            98.026835
Heads-Up_Display     95.974743
Welcome_Lights       94.554065
Battery              98.973954
Electric_Range       98.658248
Length: 141, dtype: float64

In [11]:
# Remove S.No. column from data
data = data.drop(['S.No.'], axis = 1)
data.info()

KeyError: "['S.No.'] not found in axis"

In [12]:
from datetime import date
date.today().year
data['Car_Age']=date.today().year-data['Year']
data.head()

KeyError: 'Year'